import { DemoAccountDefinition } from './authTypes';
import { DEMO_STUDENT } from '../data/demoData';

export const COMMON_DEMO_PASSWORD = 'SKILLGAP COMPASS@';

export const DEMO_STUDENT_ACCOUNTS: DemoAccountDefinition[] = [
  {
    registerNumber: '23CSE001',
    name: 'Ajay',
    role: 'student',
    department: 'Computer Science Engineering',
    year: '4th Year',
    cgpa: 8.1,
    targetCareer: 'Data Analyst',
    readinessScore: 72,
    roadmapProgress: 65,
    topGaps: ['Power BI', 'Statistics', 'Data Visualization'],
    status: 'Developing',
    profileData: DEMO_STUDENT,
    userAccount: {
      id: '23CSE001',
      name: 'Ajay',
      email: '23cse001@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (CSE)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Computer Science Engineering',
      avatarInitials: 'AJ',
      avatarColor: 'bg-indigo-600',
    },
  },
  {
    registerNumber: '23CSE002',
    name: 'Priya Patel',
    role: 'student',
    department: 'CSE',
    year: '4th Year',
    cgpa: 8.9,
    targetCareer: 'Software Developer',
    readinessScore: 88,
    roadmapProgress: 90,
    topGaps: ['System Design (Basics)', 'Docker'],
    status: 'Job Ready',
    profileData: {
      id: '23CSE002',
      fullName: 'Priya Patel',
      email: '23cse002@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'CSE',
      academicYear: '4th Year',
      cgpa: 8.9,
      targetCareerId: 'software-developer',
      skills: [
        { name: 'Java', category: 'Programming', level: 'Advanced', status: 'Completed' },
        { name: 'Data Structures & Algorithms', category: 'Programming', level: 'Advanced', status: 'Completed' },
        { name: 'SQL', category: 'Data', level: 'Intermediate', status: 'Completed' },
        { name: 'Git & GitHub', category: 'Tools', level: 'Intermediate', status: 'Completed' },
        { name: 'REST APIs', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'System Design', category: 'Programming', level: 'Beginner', status: 'Learning' },
        { name: 'Docker', category: 'Cloud', level: 'Beginner', status: 'Not Started' },
        { name: 'Technical Communication', category: 'Soft Skills', level: 'Intermediate', status: 'Completed' },
      ],
      programmingLanguages: ['Java', 'C++', 'Python'],
      tools: ['IntelliJ IDEA', 'Git', 'Postman'],
      certifications: ['Oracle Certified Associate Java Programmer'],
      internships: ['SDE Intern at CloudMatrix (Built backend microservices)'],
      projects: ['Distributed Task Scheduler', 'E-commerce API Engine'],
      interests: ['Distributed Systems', 'Backend Engineering'],
    },
    userAccount: {
      id: '23CSE002',
      name: 'Priya Patel',
      email: '23cse002@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (CSE)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Computer Science Engineering',
      avatarInitials: 'PP',
      avatarColor: 'bg-emerald-600',
    },
  },
  {
    registerNumber: '23CSE003',
    name: 'Rohan Mehta',
    role: 'student',
    department: 'IT',
    year: '4th Year',
    cgpa: 7.2,
    targetCareer: 'AI/ML Engineer',
    readinessScore: 44,
    roadmapProgress: 45,
    topGaps: ['Deep Learning', 'PyTorch', 'Linear Algebra', 'Model Deployment'],
    status: 'Critical Gap',
    profileData: {
      id: '23CSE003',
      fullName: 'Rohan Mehta',
      email: '23cse003@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'Information Technology',
      academicYear: '4th Year',
      cgpa: 7.2,
      targetCareerId: 'ai-ml-engineer',
      skills: [
        { name: 'Python', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'NumPy & Pandas', category: 'Data', level: 'Intermediate', status: 'Completed' },
        { name: 'Linear Algebra', category: 'Data', level: 'Beginner', status: 'Learning' },
        { name: 'Deep Learning', category: 'AI/ML', level: 'Beginner', status: 'Not Started' },
        { name: 'PyTorch', category: 'AI/ML', level: 'Beginner', status: 'Not Started' },
        { name: 'Model Deployment', category: 'Cloud', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['Python'],
      tools: ['Jupyter Notebook', 'Google Colab'],
      certifications: ['DeepLearning.AI Machine Learning Specialization'],
      internships: [],
      projects: ['House Price Prediction Model'],
      interests: ['Machine Learning', 'Computer Vision'],
    },
    userAccount: {
      id: '23CSE003',
      name: 'Rohan Mehta',
      email: '23cse003@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (IT)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Information Technology',
      avatarInitials: 'RM',
      avatarColor: 'bg-rose-600',
    },
  },
  {
    registerNumber: '23CSE004',
    name: 'Ananya Sen',
    role: 'student',
    department: 'CSE',
    year: '3rd Year',
    cgpa: 8.4,
    targetCareer: 'Cloud Engineer',
    readinessScore: 61,
    roadmapProgress: 60,
    topGaps: ['Kubernetes', 'Terraform (IaC)', 'AWS IAM'],
    status: 'Developing',
    profileData: {
      id: '23CSE004',
      fullName: 'Ananya Sen',
      email: '23cse004@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'CSE',
      academicYear: '3rd Year',
      cgpa: 8.4,
      targetCareerId: 'cloud-engineer',
      skills: [
        { name: 'Linux Basics', category: 'Tools', level: 'Intermediate', status: 'Completed' },
        { name: 'Python', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'AWS Core Services', category: 'Cloud', level: 'Intermediate', status: 'Completed' },
        { name: 'Docker', category: 'Cloud', level: 'Beginner', status: 'Learning' },
        { name: 'Kubernetes', category: 'Cloud', level: 'Beginner', status: 'Not Started' },
        { name: 'Terraform (IaC)', category: 'Cloud', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['Python', 'Bash'],
      tools: ['AWS Console', 'Docker', 'Git'],
      certifications: ['AWS Certified Cloud Practitioner'],
      internships: ['Cloud Trainee at NexaOps (Assisted VPC configuration)'],
      projects: ['Static Website Hosting on AWS S3 & CloudFront'],
      interests: ['DevOps', 'Cloud Architecture'],
    },
    userAccount: {
      id: '23CSE004',
      name: 'Ananya Sen',
      email: '23cse004@student.college.edu',
      role: 'student',
      designation: '3rd Year Undergraduate (CSE)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Computer Science Engineering',
      avatarInitials: 'AS',
      avatarColor: 'bg-blue-600',
    },
  },
  {
    registerNumber: '23CSE005',
    name: 'Vikram Rao',
    role: 'student',
    department: 'ECE',
    year: '4th Year',
    cgpa: 6.8,
    targetCareer: 'Software Developer',
    readinessScore: 38,
    roadmapProgress: 30,
    topGaps: ['Data Structures & Algorithms', 'Databases & SQL', 'Git/GitHub'],
    status: 'Critical Gap',
    profileData: {
      id: '23CSE005',
      fullName: 'Vikram Rao',
      email: '23cse005@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'Electronics & Communication',
      academicYear: '4th Year',
      cgpa: 6.8,
      targetCareerId: 'software-developer',
      skills: [
        { name: 'C Programming', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'Data Structures & Algorithms', category: 'Programming', level: 'Beginner', status: 'Learning' },
        { name: 'SQL', category: 'Data', level: 'Beginner', status: 'Not Started' },
        { name: 'Git & GitHub', category: 'Tools', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['C', 'C++'],
      tools: ['Keil', 'VS Code'],
      certifications: [],
      internships: [],
      projects: ['IoT Weather Station using ESP32'],
      interests: ['Embedded Systems', 'Software Engineering'],
    },
    userAccount: {
      id: '23CSE005',
      name: 'Vikram Rao',
      email: '23cse005@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (ECE)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Electronics & Communication',
      avatarInitials: 'VR',
      avatarColor: 'bg-amber-600',
    },
  },
  {
    registerNumber: '23CSE006',
    name: 'Kavita Iyer',
    role: 'student',
    department: 'IT',
    year: '4th Year',
    cgpa: 8.7,
    targetCareer: 'Data Analyst',
    readinessScore: 84,
    roadmapProgress: 85,
    topGaps: ['Advanced Tableau', 'BigQuery Optimization'],
    status: 'Job Ready',
    profileData: {
      id: '23CSE006',
      fullName: 'Kavita Iyer',
      email: '23cse006@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'Information Technology',
      academicYear: '4th Year',
      cgpa: 8.7,
      targetCareerId: 'data-analyst',
      skills: [
        { name: 'Python', category: 'Programming', level: 'Advanced', status: 'Completed' },
        { name: 'SQL', category: 'Data', level: 'Advanced', status: 'Completed' },
        { name: 'Power BI', category: 'Tools', level: 'Intermediate', status: 'Completed' },
        { name: 'Statistics', category: 'Data', level: 'Intermediate', status: 'Completed' },
        { name: 'Data Cleaning', category: 'Data', level: 'Intermediate', status: 'Completed' },
        { name: 'Tableau', category: 'Tools', level: 'Beginner', status: 'Learning' },
      ],
      programmingLanguages: ['Python', 'SQL'],
      tools: ['Power BI', 'Excel', 'Jupyter'],
      certifications: ['Google Data Analytics Professional Certificate'],
      internships: ['Data Analytics Intern at RetailAI (Built churn dashboards)'],
      projects: ['Customer Segmentation & Lifetime Value Engine', 'Supply Chain Delay Tracker'],
      interests: ['Business Analytics', 'Data Visualization'],
    },
    userAccount: {
      id: '23CSE006',
      name: 'Kavita Iyer',
      email: '23cse006@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (IT)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Information Technology',
      avatarInitials: 'KI',
      avatarColor: 'bg-purple-600',
    },
  },
  {
    registerNumber: '23CSE007',
    name: 'Karthik Subramanian',
    role: 'student',
    department: 'AI & DS',
    year: '3rd Year',
    cgpa: 8.5,
    targetCareer: 'AI/ML Engineer',
    readinessScore: 65,
    roadmapProgress: 62,
    topGaps: ['MLOps (CI/CD for ML)', 'Docker Containerization', 'Distributed Training'],
    status: 'Developing',
    profileData: {
      id: '23CSE007',
      fullName: 'Karthik Subramanian',
      email: '23cse007@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'AI & Data Science',
      academicYear: '3rd Year',
      cgpa: 8.5,
      targetCareerId: 'ai-ml-engineer',
      skills: [
        { name: 'Python', category: 'Programming', level: 'Advanced', status: 'Completed' },
        { name: 'Scikit-Learn', category: 'AI/ML', level: 'Intermediate', status: 'Completed' },
        { name: 'TensorFlow', category: 'AI/ML', level: 'Intermediate', status: 'Completed' },
        { name: 'Linear Algebra & Calculus', category: 'Data', level: 'Intermediate', status: 'Completed' },
        { name: 'Docker', category: 'Cloud', level: 'Beginner', status: 'Learning' },
        { name: 'MLOps', category: 'Tools', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['Python', 'C++'],
      tools: ['VS Code', 'Git', 'Weights & Biases'],
      certifications: ['TensorFlow Developer Certificate'],
      internships: ['ML Intern at VisionTech (Object detection for factory automation)'],
      projects: ['Automated Defect Detection with YOLOv8'],
      interests: ['Computer Vision', 'Deep Learning'],
    },
    userAccount: {
      id: '23CSE007',
      name: 'Karthik Subramanian',
      email: '23cse007@student.college.edu',
      role: 'student',
      designation: '3rd Year Undergraduate (AI & DS)',
      organization: 'National Institute of Engineering & Technology',
      department: 'AI & Data Science',
      avatarInitials: 'KS',
      avatarColor: 'bg-teal-600',
    },
  },
  {
    registerNumber: '23CSE008',
    name: 'Sneha Roy',
    role: 'student',
    department: 'EEE',
    year: '4th Year',
    cgpa: 7.9,
    targetCareer: 'Cloud Engineer',
    readinessScore: 52,
    roadmapProgress: 50,
    topGaps: ['Linux Shell Scripting', 'Networking Protocols (TCP/IP)', 'Docker Containers'],
    status: 'Developing',
    profileData: {
      id: '23CSE008',
      fullName: 'Sneha Roy',
      email: '23cse008@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'Electrical & Electronics Engineering',
      academicYear: '4th Year',
      cgpa: 7.9,
      targetCareerId: 'cloud-engineer',
      skills: [
        { name: 'Python', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'Cloud Fundamentals', category: 'Cloud', level: 'Intermediate', status: 'Completed' },
        { name: 'Linux Basics', category: 'Tools', level: 'Beginner', status: 'Learning' },
        { name: 'Networking (TCP/IP)', category: 'Tools', level: 'Beginner', status: 'Not Started' },
        { name: 'Docker', category: 'Cloud', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['Python', 'C'],
      tools: ['AWS Console', 'Wireshark'],
      certifications: ['Microsoft Certified: Azure Fundamentals (AZ-900)'],
      internships: [],
      projects: ['Smart Grid Load Balancing Simulator'],
      interests: ['Cloud Infrastructure', 'Automation'],
    },
    userAccount: {
      id: '23CSE008',
      name: 'Sneha Roy',
      email: '23cse008@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (EEE)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Electrical & Electronics Engineering',
      avatarInitials: 'SR',
      avatarColor: 'bg-pink-600',
    },
  },
  {
    registerNumber: '23CSE009',
    name: 'Arjun Das',
    role: 'student',
    department: 'CSE',
    year: '3rd Year',
    cgpa: 8.2,
    targetCareer: 'Cybersecurity Analyst',
    readinessScore: 58,
    roadmapProgress: 55,
    topGaps: ['Wireshark Network Analysis', 'SIEM / Splunk', 'Penetration Testing Tools'],
    status: 'Developing',
    profileData: {
      id: '23CSE009',
      fullName: 'Arjun Das',
      email: '23cse009@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'Computer Science Engineering',
      academicYear: '3rd Year',
      cgpa: 8.2,
      targetCareerId: 'cybersecurity-analyst',
      skills: [
        { name: 'Network Security Fundamentals', category: 'Tools', level: 'Intermediate', status: 'Completed' },
        { name: 'Linux Administration', category: 'Tools', level: 'Intermediate', status: 'Completed' },
        { name: 'Python for Security', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'Wireshark', category: 'Tools', level: 'Beginner', status: 'Learning' },
        { name: 'SIEM / Splunk', category: 'Tools', level: 'Beginner', status: 'Not Started' },
        { name: 'Vulnerability Scanning', category: 'Tools', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['Python', 'Bash'],
      tools: ['Kali Linux', 'Wireshark', 'Nmap'],
      certifications: ['CompTIA Security+ Certified'],
      internships: ['Cyber Defense Intern at NetShield (Firewall log analysis)'],
      projects: ['Automated Port Scanner & Vulnerability Reporter'],
      interests: ['Cyber Threat Intelligence', 'SOC Operations'],
    },
    userAccount: {
      id: '23CSE009',
      name: 'Arjun Das',
      email: '23cse009@student.college.edu',
      role: 'student',
      designation: '3rd Year Undergraduate (CSE)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Computer Science Engineering',
      avatarInitials: 'AD',
      avatarColor: 'bg-cyan-600',
    },
  },
  {
    registerNumber: '23CSE010',
    name: 'Meera Nair',
    role: 'student',
    department: 'IT',
    year: '4th Year',
    cgpa: 9.1,
    targetCareer: 'Data Analyst',
    readinessScore: 79,
    roadmapProgress: 75,
    topGaps: ['Advanced Power BI DAX', 'Data Warehousing'],
    status: 'Job Ready',
    profileData: {
      id: '23CSE010',
      fullName: 'Meera Nair',
      email: '23cse010@student.college.edu',
      college: 'National Institute of Engineering & Technology',
      department: 'Information Technology',
      academicYear: '4th Year',
      cgpa: 9.1,
      targetCareerId: 'data-analyst',
      skills: [
        { name: 'SQL', category: 'Data', level: 'Advanced', status: 'Completed' },
        { name: 'Python', category: 'Programming', level: 'Intermediate', status: 'Completed' },
        { name: 'Excel & Financial Modeling', category: 'Tools', level: 'Advanced', status: 'Completed' },
        { name: 'Tableau', category: 'Tools', level: 'Intermediate', status: 'Completed' },
        { name: 'Power BI', category: 'Tools', level: 'Beginner', status: 'Learning' },
        { name: 'Data Warehousing', category: 'Data', level: 'Beginner', status: 'Not Started' },
      ],
      programmingLanguages: ['SQL', 'Python', 'R'],
      tools: ['Tableau', 'Excel', 'Power BI'],
      certifications: ['Tableau Desktop Specialist', 'Google Advanced Data Analytics'],
      internships: ['Business Intelligence Intern at FinTech Global'],
      projects: ['Quarterly Sales Forecast & Attribution Dashboard'],
      interests: ['Financial Analytics', 'Business Intelligence'],
    },
    userAccount: {
      id: '23CSE010',
      name: 'Meera Nair',
      email: '23cse010@student.college.edu',
      role: 'student',
      designation: '4th Year Undergraduate (IT)',
      organization: 'National Institute of Engineering & Technology',
      department: 'Information Technology',
      avatarInitials: 'MN',
      avatarColor: 'bg-violet-600',
    },
  },
];

export const DEMO_STAFF_ACCOUNTS: DemoAccountDefinition[] = [
  {
    registerNumber: 'STAFF001',
    name: 'Dr. Sarah Jenkins',
    role: 'staff',
    department: 'Dept. of Computer Science & Engineering',
    designation: 'Associate Professor & Career Placement Mentor',
    userAccount: {
      id: 'STAFF001',
      name: 'Dr. Sarah Jenkins',
      email: 's.jenkins@faculty.college.edu',
      role: 'staff',
      designation: 'Associate Professor & Career Placement Mentor',
      organization: 'National Institute of Engineering & Technology',
      department: 'Dept. of Computer Science & Engineering',
      avatarInitials: 'SJ',
      avatarColor: 'bg-emerald-600',
    },
  },
  {
    registerNumber: 'STAFF002',
    name: 'Dr. Ramesh Varma',
    role: 'staff',
    department: 'Dept. of Information Technology',
    designation: 'Professor & Placement Coordinator',
    userAccount: {
      id: 'STAFF002',
      name: 'Dr. Ramesh Varma',
      email: 'r.varma@faculty.college.edu',
      role: 'staff',
      designation: 'Professor & Placement Coordinator',
      organization: 'National Institute of Engineering & Technology',
      department: 'Dept. of Information Technology',
      avatarInitials: 'RV',
      avatarColor: 'bg-teal-600',
    },
  },
  {
    registerNumber: 'STAFF003',
    name: 'Prof. Neha Gupta',
    role: 'staff',
    department: 'Dept. of Electronics & Communication',
    designation: 'Assistant Professor & Technical Training Incharge',
    userAccount: {
      id: 'STAFF003',
      name: 'Prof. Neha Gupta',
      email: 'n.gupta@faculty.college.edu',
      role: 'staff',
      designation: 'Assistant Professor & Technical Training Incharge',
      organization: 'National Institute of Engineering & Technology',
      department: 'Dept. of Electronics & Communication',
      avatarInitials: 'NG',
      avatarColor: 'bg-indigo-600',
    },
  },
];

export const DEMO_CAMPUS_ACCOUNTS: DemoAccountDefinition[] = [
  {
    registerNumber: 'ADMIN001',
    name: 'Prof. Rajesh Sharma',
    role: 'campus',
    department: 'Campus Leadership & Placement Cell',
    designation: 'Dean of Academics & Corporate Placement Director',
    userAccount: {
      id: 'ADMIN001',
      name: 'Prof. Rajesh Sharma',
      email: 'dean.placements@niet.edu',
      role: 'campus',
      designation: 'Dean of Academics & Corporate Placement Director',
      organization: 'National Institute of Engineering & Technology',
      department: 'Campus Leadership & Placement Cell',
      avatarInitials: 'RS',
      avatarColor: 'bg-amber-600',
    },
  },
  {
    registerNumber: 'ADMIN002',
    name: 'Dr. Anand Kulkarni',
    role: 'campus',
    department: 'Principal Secretariat & Corporate Relations',
    designation: 'Principal & Chief Placement Officer',
    userAccount: {
      id: 'ADMIN002',
      name: 'Dr. Anand Kulkarni',
      email: 'principal@niet.edu',
      role: 'campus',
      designation: 'Principal & Chief Placement Officer',
      organization: 'National Institute of Engineering & Technology',
      department: 'Principal Secretariat & Corporate Relations',
      avatarInitials: 'AK',
      avatarColor: 'bg-orange-600',
    },
  },
];

export const ALL_DEMO_ACCOUNTS = [
  ...DEMO_STUDENT_ACCOUNTS,
  ...DEMO_STAFF_ACCOUNTS,
  ...DEMO_CAMPUS_ACCOUNTS,
];
